### ISSUE TITLE
stepdefs formatter crashes with undefined method step_definition for nil:NilClass

### ISSUE THREAD

**Issue by JeanMertz** [cucumber/cucumber-ruby#953] opened 2016-03-15 12:10 UTC
```
bundle exec cucumber -f stepdefs
...................................................................undefined method `step_definition' for nil:NilClass (NoMethodError)
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/formatter/usage.rb:29:in `after_test_step'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/formatter/legacy_api/adapter.rb:38:in `after_test_step'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/formatter/fanout.rb:15:in `each'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/filters/quit.rb:11:in `test_case'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/filter.rb:61:in `done'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/compiler.rb:23:in `done'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core/gherkin/parser.rb:39:in `done'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:29:in `parse'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-core-1.4.0/lib/cucumber/core.rb:18:in `compile'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/runtime.rb:68:in `run!'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/Jean/.gem/ruby/2.3.0/gems/cucumber-2.3.2/bin/cucumber:8:in `<top (required)>'
/Users/Jean/.gem/ruby/2.3.0/bin/cucumber:23:in `load'
/Users/Jean/.gem/ruby/2.3.0/bin/cucumber:23:in `<main>'
```

**Comment by mattwynne** [comment] 2016-03-15 14:26
Can you share an example of a feature file that causes this crash please?

**Comment by dg-ratiodata** [comment] 2016-03-22 11:48
@mattwynne You can reproduce the issue using `cucumber`'s own features. Just have a look at #955.

**Comment by bugthing** [comment] 2016-06-17 12:21
If it's any use, I am seeing this problem using `--format usage`

Here is the output of a bundle install then running cucumber:

```
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using addressable 2.4.0
Using awesome_print 1.6.1
Using builder 3.2.2
Using byebug 9.0.4
Using mime-types-data 3.2016.0521
Using mini_portile2 2.0.0
Using rack 1.6.4
Using ffi 1.9.10
Using cliver 0.3.2
Using coderay 1.1.1
Installing gherkin 4.0.0
Using cucumber-wire 0.0.1
Using diff-lcs 1.2.5
Using multi_json 1.12.1
Using multi_test 0.1.2
Using dotenv 2.1.1
Using rack-idempotent 0.2.0
Using method_source 0.8.2
Using parallel 1.8.0
Using websocket-extensions 0.1.2
Using slop 3.6.0
Using rspec-support 3.4.1
Using rubyzip 1.2.0
Using websocket 1.2.3
Using bundler 1.12.5
Using faker 1.6.3
Using tzinfo 1.2.2
Using launchy 2.4.3
Using mime-types 3.1
Using nokogiri 1.6.7.2
Using rack-test 0.6.3
Using rack-client 0.4.2
Using childprocess 0.5.9
Installing cucumber-core 1.5.0
Using websocket-driver 0.6.4
Using pry 0.10.3
Using rspec-core 3.4.4
Using rspec-expectations 3.4.0
Using rspec-mocks 3.4.1
Using activesupport 4.2.6
Using mail 2.6.4
Using xpath 2.0.0
Using ey_api_hmac 0.4.12
Using selenium-webdriver 2.53.0
Installing cucumber 2.4.0
Using pry-byebug 3.4.0
Using rspec 3.4.0
Using capybara 2.7.1
Using wp-hmac 0.2.5
Using capybara-angular 0.2.3
Using capybara-screenshot 1.0.13
Using poltergeist 1.9.0
Using site_prism 2.9
Bundle complete! 18 Gemfile dependencies, 58 gems now installed.

bundle exec cucumber --format usage --require=support/ --require=suites/common/step_definitions --require=suites/schedule/step_definitions --exclude=suites/schedule/features/browserstack suites/schedule/features
..................................................................................undefined method `step_definition' for nil:NilClass (NoMethodError)
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/usage.rb:29:in `after_test_step'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:38:in `after_test_step'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:106:in `block (2 levels) in compose_around_hooks'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:18:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/opt/rubies/2.3.1/bin/cucumber:23:in `load'
/opt/rubies/2.3.1/bin/cucumber:23:in `<top (required)>'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/rubies/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/rubies/2.3.1/bin/bundle:23:in `load'
/opt/rubies/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by tejasv02** [comment] 2016-11-24 17:32
+1

**Comment by brasmusson** [comment] 2016-11-24 20:05
I close this issue because in #977, which is in v3.0.0.pre.1, the usage formatter was changed so it does not have an `after_test_step` method and does not use the `legacy_api` any longer, therefore the stacktrace above is not possible. Should this kind of problem still exist with the usage formatter in v3.0.0.pre.1, which is highly unlikely since the `legacy_api` is the likely source of this problem, a new issue with the new stacktrace should be opened.

**Closed by brasmusson** 2016-11-24 20:05 UTC
