### ISSUE TITLE
Get error "undefined method `tags' for nil:NilClass (NoMethodError)" on ubuntu when run command: cucumber BROWSER='chrome-desktop-headless' 

### ISSUE THREAD

**Issue by IrisLiu001** [cucumber/cucumber-ruby#1616] opened 2022-02-24 07:42 UTC
### 👓 What did you see?
Get error "undefined method `tags' for nil:NilClass (NoMethodError)" on ubuntu when run command: cucumber BROWSER='chrome-desktop-headless' 

### 📦 Which version are you using?
source "https://rubygems.org"

gem 'allure-cucumber', '2.13.6'
gem 'browser'
gem 'cucumber', '4.0'
gem 'parallel_tests', '3.0'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'rspec-expectations', '~> 3.3.0'
gem 'rubocop'
gem 'selenium-webdriver',         '3.141'
gem 'selenium_remote_control',    '~> 1.0', '>= 1.0.4'
gem 'rest-client',                '~> 2.0'
gem 'net-http-persistent',        '~> 3.0'
gem 'faker',    '2.11'
gem 'cuke_modeler', '3.0'

1. Trigger github actions
2. actions start run and execute the command in actions: cucumber BROWSER='chrome-desktop-headless' 

![image](https://user-images.githubusercontent.com/89027578/155479803-ef9a825e-edea-48c4-819e-9b46e3c9f9d8.png)

**Comment by aurelien-reeves** [comment] 2022-02-24 08:20
Well `cucumber BROWSER='chrome-desktop-headless'` seems not to be a valid command.

If you want to run cucumber with the `BROWSER` env variable set with `chrome-desktop-headless`, you should run the following instead: `BROWSER='chrome-desktop-headless' cucumber`

And actually I see in your screenshot that you already have an `BROWSER: chrome-headless` env in your job.

What are you trying to achieve? Could you make sure your workflow and your command are right?

**Comment by IrisLiu001** [comment] 2022-02-24 09:35
> Well `cucumber BROWSER='chrome-desktop-headless'` seems not to be a valid command.
> 
> If you want to run cucumber with the `BROWSER` env variable set with `chrome-desktop-headless`, you should run the following instead: `BROWSER='chrome-desktop-headless' cucumber`
> 
> And actually I see in your screenshot that you already have an `BROWSER: chrome-headless` env in your job.
> 
> What are you trying to achieve? Could you make sure your workflow and your command are right?

Thank you for reply.
I just tried your command : BROWSER='chrome-desktop-headless' cucumber
still get the same error, this error should not be caused by the command format, since it runs pass on ubuntu one month ago, as you can see below.
And no matter which command i run on local, both works fine; in addition, BROWSER: chrome-headless env can be deleted, it doesn't matter.
I guess it should be related to the cucumber version installed on ubuntu, since I see someone else met this issue, and say this is a cucumber bug: https://community.smartbear.com/t5/Cucumber-Open/feature-is-coming-up-nil-in-query-rb/td-p/202827
![image](https://user-images.githubusercontent.com/89027578/155497347-488b5133-7c1f-4ddc-bd88-6afe4a2007e2.png)

**Comment by luke-hill** [comment] 2022-02-24 09:39
Unfortunately this information isn't enough for us to reproduce this. Could you create an [SSCCE](http://sscce.org/) / [MVCE](https://stackoverflow.com/help/minimal-reproducible-example), so we can reproduce this.

The best form is in the form of a github repo, as then we just pull down the code and run it.

**Comment by aurelien-reeves** [comment] 2022-02-24 09:42
In adition to cucumber 4, I noticed in the link you submit to the smartbear community forum that it seems your are still using ruby 2.3.

ruby 2.3 and cucumber 4 are very old version for ruby and cucumber and are not maintain anymore for a long time now. You should consider upgrading ruby and cucumber to latest version before anything else.

**Comment by aurelien-reeves** [comment] 2022-02-24 09:54
> Thank you for reply. I just tried your command : BROWSER='chrome-desktop-headless' cucumber still get the same error

Do you have more info? Did you tried it on your own computer or in the CI?

> this error should not be caused by the command format, since it runs pass on ubuntu one month ago, as you can see below.

If a command is not well formed, it can cause issues 🤔
And the picture you submit does not show the same command as you are trying to use today.

> And no matter which command i run on local, both works fine; in addition, BROWSER: chrome-headless env can be deleted, it doesn't matter.

So, please make sure to submit a decent issue with a minimal reproducible example. If the env is not relevant, then do not make it part of the issue

> I guess it should be related to the cucumber version installed on ubuntu,

cucumber is not installed on ubuntu. This is not a "ubuntu" thing. This is a ruby gem. It depends on your project, and on your version of ruby. Not on ubuntu

> since I see someone else met this issue, and say this is a cucumber bug: https://community.smartbear.com/t5/Cucumber-Open/feature-is-coming-up-nil-in-query-rb/td-p/202827 

This is 2 years old and was based on really old version of ruby and cucumber. This is certainly not relevant anymore.

As you are yourself using a pretty old version of cucumber, first thing would be to update it. If a bug has been found 2 years ago, it may have been fixed in more recent version of cucumber.

As @luke-hill said: please try to update cucumber and ruby, and to submit a clear, neat and comprehensive minimal reproducible example. At the moment there is nothing we can do to help.

**Comment by IrisLiu001** [comment] 2022-02-24 09:55
yep, I thought it's due to cucumber's version too old, and tried 5.0, 6.0, 7.0 and so on, but keeps get below error when the version is not 4.0. So I guess maybe it is limitation on ubuntu, that cannot support enough versions of cucumber.
![image](https://user-images.githubusercontent.com/89027578/155501222-73072bb7-fa35-4942-9e7a-ea468b2a9614.png)

**Comment by aurelien-reeves** [comment] 2022-02-24 09:57
This is not related to ubuntu.

Please look at the error message: here it says that it has not been able to find a compatible version due to non compatible dependencies in your gemfile. Nothing to do with cucumber here.

**Comment by aurelien-reeves** [comment] 2022-02-24 09:58
Also, your "step to reproduce" actually do not help us to reproduce your issue.

We have not the capability to trigger your own github workflow.

Are you a ruby developer?
What are you trying to achieve here? Are you responsible for your project tests? Or maintenance?

**Comment by IrisLiu001** [comment] 2022-02-24 10:14
New learner on ruby and cucumber.
The ruby- 2.7.5 cucumber-4.0.0 version works fine on my local, see below:
![image](https://user-images.githubusercontent.com/89027578/155504466-f5fa3ab3-acaf-46b0-8d28-69a28e203efd.png)

Now I have design about 20 automation cases locally, so I would like to integrate with CI.
The cucumber command run fail on ubuntu after CI triggered

**Comment by aurelien-reeves** [comment] 2022-02-24 10:18
Stop putting `BROWSER='chrome-desktop-headless'` after your cucumber command!
This is not save and error-prone. If you need to set that env variable, put it before the cucumber command, or in your environment, or in a .env file, or whatever, but it has nothing to do after the cucumber command

Also, please upgrade to the last version of cucumber. cucumber 4 is old and not maintained anymore.

We won't be able to help you more until you use a proper command line instruction, and you use a more recent cucumber.

**Closed** 2022-02-24 14:33 UTC

**Comment by IrisLiu001** [comment] 2022-02-28 02:20
Thank you all the the reply.
Update ruby to 3.0 and cucumber to 7.1. solve this problem.

**Comment by aurelien-reeves** [comment] 2022-02-28 08:50
Just to prevent other from being misled: no, this is not a compatibility issue between cucumber-ruby and ubuntu.

@IrisLiu001 I don't know how you conclude such compatibility issue but I assure you this is not the case. Cucumber-ruby is a ruby gem in plain ruby. There may be issues based on operating systems, but that was definitely not the case here, and nothing point in that direction.

It was most likely an issue in a previous cucumber version that has been fixed in more recent versions.
