### ISSUE TITLE
Formulation of steps is seen as an irregularity? [Ruby]

### ISSUE THREAD

**Issue by BoWunder** [cucumber/cucumber-ruby#1558] opened 2021-07-05 09:02 UTC
**Describe the bug**
Not sure if this is a bug or I have misunderstood details in Gherkin, but I have now twice experienced, that the formulation of my steps have been seen as "failed" - not due to the code itself, but to the wording of the "Given", "When", and "Then".

**To Reproduce**
There are no actual steps I can refer to, to replicate these happenings. Best I can do is to refer to the examples below and the provided material.

Considering that Cucumber is supposed to allow a more free formulation of steps, then this seems odd.

For example, "When I ask whether it's Friday yet" is seen as an error, while "When I ask if it is Friday yet" is seen as correct (see the blue markings in images "Cucumber Grammatics 01" and "Cucumber Grammatics 02").

Another Example is how "Then I should be told the answer" is seen as wrong, while "Then I should get the answer" is seen as correct" (see the yellow markings in images "Cucumber Grammatics 02" and "Cucumber Grammatics 03").

**Expected behavior**

I would expect that the wording used for the steps would be of little important (not counting the actual coding in the _step.rb file). It is clear that Cucumber (or maybe Ruby?) does not recognize certain words or formulations of a sentence. That is quite an issue, as I would then suspect that the use of certain slang / business-related terms would/could produce a similar false-negative.

**Context & Motivation**

Context is the worry, that the use of client-specific terms, business-lingo or wordings would cause false-negatives.

**Screenshots**
<img width="535" alt="Cucumber Grammatics 01" src="https://user-images.githubusercontent.com/86303765/124445380-c9bb1c00-dd7f-11eb-8d84-5a5c3aa1cf17.PNG">
<img width="539" alt="Cucumber Grammatics 02" src="https://user-images.githubusercontent.com/86303765/124445382-ca53b280-dd7f-11eb-97cc-18c7629455ac.PNG">
<img width="530" alt="Cucumber Grammatics 03" src="https://user-images.githubusercontent.com/86303765/124445386-caec4900-dd7f-11eb-89bf-bfef522d6517.PNG">

**Your Environment**
 - Versions used [Ruby30-x64]
 - Operating System and version: [Windows 10 Pro]
 - Build tool: [Rubymine 2021.1.2.]

**Additional context**
Posting Code Here (fixed and non-fixed)

####[Feature File (non-fixed)]:
Feature: is it Friday yet?
  Everybody wants to know when it's Friday

  Scenario: Sunday is or is not Friday
    Given today is maybe Friday
    When I ask whether it's Friday yet
    Then I should be told the answer

####[Feature File (fixed)]:
Feature: is it Friday yet?
  Everybody wants to know when it's Friday

  Scenario: Sunday is or is not Friday
    Given today is maybe Friday
    When I ask if it is Friday yet
    Then I should get the answer

####[_step.rb (non-fixed)]
Given(/^today is maybe Friday$/) do #|current_day|
  current_day = Date.today.friday?
  if current_day == 1
      @ans = "Yes!"
      @today = "Friday"
   else
      @ans = "Nope..."
      @today = "not Friday"
  end
end

When(/^I ask whether it's Friday yet$/) do
  puts "Is it Friday today?"
end

Then(/^I should be told the answer$/) do #|answer|
  puts "Today is #{@today}."
  puts "So in short; #{@ans}"
end

####[_step.rb (fixed)]
Given(/^today is maybe Friday$/) do #|current_day|
  current_day = Date.today.friday?
  if current_day == 1
      @ans = "Yes!"
      @today = "Friday"
   else
      @ans = "Nope..."
      @today = "not Friday"
  end
end

When(/^I ask if it is Friday yet$/) do
  puts "Is it Friday today?"
end

Then(/^I should get the answer$/) do #|answer|
  puts "Today is #{@today}."
  puts "So in short; #{@ans}"
end

**Comment by aurelien-reeves** [comment] 2021-07-05 09:19
> Considering that Cucumber is supposed to allow a more free formulation of steps, then this seems odd.

Yes, Cucumber can allow a more free formulation of steps, but this remain a software. There is no magic behind it. Some development still has to be made as part of the automation process to tell Cucumber how to recognize steps. Cucumber uses [cucumber expressions](https://cucumber.io/docs/cucumber/cucumber-expressions/) to match steps with actual code.

For the errors you encountered, from what I can see, Cucumber actually does not has issue recognizing your steps. It seems you have some code duplication in IsItFriday_step.rb and whenfriday_step.rb. Cucumber found two possible way to execute your step and cannot decide which one to use.

As suggested, you could execute cucumber with `--guess` to make it pick one way. But it would be better to actually remove the duplication.

I guess it has been fixed later because you may have update your formulation, and one of the two steps in the code, so that removed the duplication.

**Comment by mattwynne** [comment] 2021-07-05 18:45
@BoWunder does this make sense now? The "Ambiguous match" error is caused by you having multiple definitions for the same step. It's nothing to do with how you've worded it.

**Comment by mattwynne** [comment] 2021-07-05 18:46
@BoWunder does this make sense now? The "Ambiguous match" error is caused by you having multiple definitions for the same step. It's nothing to do with how you've worded it.

By the way, if you're new to Cucumber you might want to check out the free video course: https://school.cucumber.io/courses/bdd-with-cucumber-ruby

**Comment by aurelien-reeves** [comment] 2021-07-13 09:35
I am closing this as it seems there is no issue with cucumber here and we went further in [another discussion](https://github.com/cucumber/cucumber-ruby/issues/1560)

**Closed by aurelien-reeves** 2021-07-13 09:35 UTC
Labels: :baby_bottle: incomplete
