### ISSUE TITLE
cucumber-expressions wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by langalex** [cucumber/cucumber-ruby#1292] opened 2018-04-23 10:22 UTC
## Summary

Just upgraded:

cucumber (3.0.2 → 3.1.0)
cucumber-core (3.0.0 → 3.1.0)
cucumber-expressions (4.0.4 → 5.0.17)
cucumber-tag_expressions (1.0.1 → 1.1.1)
gherkin (4.1.3 → 5.0.0) 
cucumber-rails (1.5.0 → 1.6.0)

and now I'm getting a `wrong number of arguments (given 0, expected 1) (ArgumentError)` in _cucumber-expressions_.

## Expected Behavior

There should be no ArgumentError.

## Current Behavior

When running my tests, I get an ArgumentError in `cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type_registry.rb:17:in `block in initialize'`.

Stacktrace:

```
cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type_registry.rb:17:in `block in initialize'
cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type.rb:38:in `instance_exec'
cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type.rb:38:in `transform'
cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/argument.rb:33:in `value'
cucumber-3.1.0/lib/cucumber/step_match.rb:18:in `block in args'
cucumber-3.1.0/lib/cucumber/step_match.rb:17:in `map'
cucumber-3.1.0/lib/cucumber/step_match.rb:17:in `args'
cucumber-3.1.0/lib/cucumber/step_match.rb:97:in `deep_clone_args'
cucumber-3.1.0/lib/cucumber/step_match.rb:29:in `invoke'
cucumber-3.1.0/lib/cucumber/step_match.rb:24:in `block in activate'
...
```

## Possible Solution

The line causing the error looks like this:

    define_parameter_type(ParameterType.new('int', INTEGER_REGEXPS, Integer, lambda {|s| s.to_i}, true, true))

The error comes from the arity of the `lambda` being one, but it's called in `paramter_type.rb:38` with no args: `self_obj.instance_exec(*group_values, &@transformer)` (`@transformer` is the lambda from above).

I have no idea what's going on there, but there's already [another commit fixing the arity of other lambdas](https://github.com/cucumber/cucumber-expressions-ruby/commit/86025db8d2bc96b5f5f5bc290ed4ecb5640eeedc). Could this be connected?

## Steps to Reproduce (for bugs)

1. upgrade cucumber-expressions to 5.0.17
2. run tests 

Sorry this is happening in a closed source repo. I can try to create a small test repo to expose the problem, but maybe it's a quick fix for someone who knows more about the code base.

## Context & Motivation

Tests are broken.

## Your Environment

* Version used: cucumber-expressions 5.0.17, Ruby 2.3.6
* Operating System and version: MacOS 10.13.4
* Link to your project: -

**Comment by viraptor** [comment] 2018-05-11 01:26
Possibly related issue https://github.com/cucumber/cucumber/issues/375 - does it work with expressions 5.0.15?

**Comment by langalex** [comment] 2018-05-11 09:51
Yes, 5.0.15 works.

**Comment by langalex** [comment] 2018-05-11 10:36
with `gem 'cucumber', git: 'git://github.com/cucumber/cucumber-ruby.git'` (including cucumber-expressions 5.0.17) everything is green 👍

**Comment by xtrasimplicity** [comment] 2018-05-11 10:36
Brilliant, thanks for confirming that, @langalex!

**Comment by langalex** [comment] 2018-05-11 10:40
@xtrasimplicity thanks for putting in the time!

**Comment by xtrasimplicity** [comment] 2018-05-11 10:44
Not a problem. I'll close this one off for the moment as it will be resolved with the release of 3.1.1. :)

**Comment by aslakhellesoy** [comment] 2018-05-11 11:29
@xtrasimplicity - https://github.com/cucumber/cucumber/pull/380 isn't released yet, so I'm not sure the bug is fixed.

@langalex can you provide us with a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) in a git repo please? We need that to reproduce the bug and verify that it's fixed.

**Comment by xtrasimplicity** [comment] 2018-05-11 11:40
Thanks @aslakhellesoy. I've reopened this in the meantime. Did you want me to hold off on releasing `cucumber-ruby 3.1.1` until the latest changes to `cucumber-expressions` are released?

**Comment by aslakhellesoy** [comment] 2018-05-11 11:49
Yes please

**Comment by langalex** [comment] 2018-05-11 12:42
@aslakhellesoy [sure](https://github.com/langalex/cucumber-bug)

**Comment by aslakhellesoy** [comment] 2018-05-11 12:52
@langalex `bundle exec cucumber` passes for me in that repo. Are you seeing something else?

**Comment by langalex** [comment] 2018-05-11 12:54
@aslakhellesoy well, it does fail [on travis](https://travis-ci.com/langalex/cucumber-bug/builds/73141907). I ran `bundle exec cucumber features/test.feature` but same with just `bundle exec cucumber`.

**Comment by langalex** [comment] 2018-05-11 12:55
also, it's still [failing](https://travis-ci.com/langalex/cucumber-bug/builds/73142431) with `gem 'cucumber', git: 'git://github.com/cucumber/cucumber-ruby.git'` ([cucumber-master branch](https://github.com/langalex/cucumber-bug/tree/cucumber-master)). but it works with cucumber-expressions 5.0.15.

**Comment by aslakhellesoy** [comment] 2018-05-12 00:05
I ran it on Ruby 2.5.1, where it passes. Then tried on 2.3.6, where it fails.

This needs some more investigation. Thanks for the mcve @langalex - that will make it easier to fix.

**Comment by xtrasimplicity** [comment] 2018-05-16 21:54
Thanks for investigating this, @alexbaranovskyi!

**Comment by xtrasimplicity** [comment] 2018-05-24 12:05
I can confirm that v5.0.18 (from the [source](https://github.com/cucumber/cucumber-expressions-ruby)) works for me with the changes made in https://github.com/cucumber/cucumber/pull/380/files#diff-0035aaedf2d4a9c0687063ec6d379192, on Ruby 2.3.6, 2.4.3 and 2.5.0, with the CVE that @langalex posted. :+1:

**Comment by xtrasimplicity** [comment] 2018-07-23 12:57
Thanks, @langalex!

**Closed by xtrasimplicity** 2018-07-23 12:57 UTC
