### ISSUE TITLE
RuntimeError when using the hashes method right after transforming the headers with map_headers! under conditions

### ISSUE THREAD

**Issue by apantsiop** [cucumber/cucumber-ruby#1490] opened 2020-11-24 14:49 UTC
**Summary**
When using the `map_headers!` method if there are headers with similar names then an error occurs when calling the `hashes` method.

**To Reproduce**

Given an test such as:

```
Given the app defines the following languages:
    | KEY     | NAME    | SHORT_NAME |
    | en      | English | en         |
    | de      | German  | de         |

Given(/^the app defines the following languages:$/) do |table|
  table.map_headers! &:downcase
  puts table.hashes
end
```
it raises error:

```
Given the repository defines the following languages:                    
      | KEY     | NAME    | SHORT_NAME |
      | en      | English | en         |
      | de      | German  | de         |
      2 headers matched "NAME": ["NAME", "SHORT_NAME"] (RuntimeError)
```

**Expected behavior**
print:
```
[{"key"=>"en", "name"=>"English", "short_name"=>"en"}, {"key"=>"de", "name"=>"German", "short_name"=>"de"}]
```

**Your Environment**
 - Versions used: 5.1.8
 - Ubuntu 20.04

**Notes**
I think the culprit is here: https://github.com/cucumber/cucumber-ruby/commit/04c4f3d5b23a05b323388a1e9c690a378dc85dbd#diff-d8aa17afd84fded9eb43fbbef970b3bdea7b824d01b975ea0b1f40bb14720efd

because by using a regex match both headers are matched

**Comment by luke-hill** [comment] 2020-11-24 15:08
Duplicate of #1450

**Closed by luke-hill** 2020-11-24 15:08 UTC
