### ISSUE TITLE
"Parameter types cannot be optional" error when parentheses used around parameters

### ISSUE THREAD

**Issue by peagha** [cucumber/cucumber-ruby#1337] opened 2018-12-19 23:32 UTC
## Summary
I cannot map a step using Cucumber Expressions when I have parentheses around a parameter. The parenthesis is already [escaped](https://docs.cucumber.io/cucumber/cucumber-expressions/#escaping).

## Expected Behavior

Given a feature:
```feature
# language: en

Feature: Parenthesis
  Scenario: Parenthesis arount a param
    Given an int is inside parenthesis like this (1)
```
and a step definition:
```ruby
Given('an int is inside parenthesis like this \({int})') do |int|
  pending # Write code here that turns the phrase above into concrete actions
end
```
When i run `cucumber`
Then it should succeed

## Current Behavior

It fails with the message:
```
Parameter types cannot be optional: an int is inside parenthesis like this \({int}) (Cucumber::CucumberExpressions::CucumberExpressionError)
```
<details>

```
Parameter types cannot be optional: an int is inside parenthesis like this \({int}) (Cucumber::CucumberExpressions::CucumberExpressionError)
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/cucumber_expression.rb:101:in `check_no_parameter_type'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/cucumber_expression.rb:54:in `block in process_optional'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/cucumber_expression.rb:52:in `gsub'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/cucumber_expression.rb:52:in `process_optional'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-expressions-6.0.1/lib/cucumber/cucumber_expressions/cucumber_expression.rb:24:in `initialize'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:154:in `new'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:154:in `create_expression'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/step_definition.rb:30:in `new'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:83:in `register_rb_step_definition'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/dsl.rb:31:in `register_rb_step_definition'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/dsl.rb:133:in `register_rb_step_definition'
/Users/peagha/Code/me/exemplos_livro/data_table/features/step_definitions/parenthesis.rb:3:in `<top (required)>'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/glue/registry_and_more.rb:107:in `load_code_file'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:144:in `load_file'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:85:in `block in load_files!'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `each'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime/support_code.rb:84:in `load_files!'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:272:in `load_step_definitions'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/runtime.rb:68:in `run!'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/lib/cucumber/cli/main.rb:34:in `execute!'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/cucumber-3.1.2/bin/cucumber:9:in `<top (required)>'
/Users/peagha/.rbenv/versions/2.5.3/bin/cucumber:23:in `load'
/Users/peagha/.rbenv/versions/2.5.3/bin/cucumber:23:in `<top (required)>'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:463:in `exec'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/cli.rb:18:in `start'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:30:in `block in <top (required)>'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/peagha/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.17.1/exe/bundle:22:in `<top (required)>'
/Users/peagha/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/peagha/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
```
</details>

## Possible Solution

It seems to be related to the [regexes used to validate the expression](https://github.com/cucumber/cucumber-expressions-ruby/blob/a4b4f1c179b1edc174ab7cb0398f58a13cd31b98/lib/cucumber/cucumber_expressions/cucumber_expression.rb#L9-L15).

## Steps to Reproduce (for bugs)

The code above should be enough. If you need more info (maybe a Github repo) just tell me and I create one.

## Context & Motivation

I'm updating a book that talks about Cucumber and RSpec. The regex examples are being replaced with Cucumber expressions, and I stepped into this problem when updating one of the examples of the book.

## Your Environment

* Version used: Cucumber 3.1.2 (fails with `4.0.0.rc.1` as well)
* Operating System and version: macOS High Sierra
* Ruby 2.5.3

**Comment by luke-hill** [comment] 2018-12-20 16:56
It seems as though you're having 2 conflicting statements (Optional stuff inside bracket literals and a parameter-type)

A workaround (albeit not fixing the issue), would be to create a custom parameter type that has enforced brackets. i.e. `/\(\d+\)/` and call it something like `bracketed_number`

Then you could say `Given('an int is inside parenthesis like this {bracketed_number}') do |int|`

**Comment by peagha** [comment] 2018-12-20 17:13
@luke-hill thanks for your answer!

I don't know if I got something wrong, but I expected that by escaping the parentheses I wouldn't have it interpreted as optional; I don't mean to use the "optional" feature at all. 

If the parentheses are escaped, what makes sense to me is for them to work just like any literal text. Do you see this scenario as an issue or Cucumber is behaving as expected?

**Comment by luke-hill** [comment] 2018-12-20 17:15
So I've spent a bit of time diving into the expressions stuff, and know a bit how it works. I think more-often than not these are edge cases which are either uncovered or conflicting.

So with this, the example shows using brackets to wrap some form of "regular" regex. However you're using a cuke-exp (Pre-defined), inside the brackets. Which are 2 different items, which could conflict.

I'll have a little play around and see if we can get the two playing nicely together.

**Comment by luke-hill** [comment] 2018-12-20 17:49
So I can see where it is failing. But I've managed to get a simple runthrough working.

Also for some reason the master branch is tracking version 6.2.1 but on rubygems only version 6.0.1 is released. Can you try hitting master, as there was some commits in recently which look at this issue (By commit msg)

**Comment by peagha** [comment] 2018-12-28 20:18
I ended up creating a repo for reproducing the error: https://github.com/peagha/cucumber_parameter_issue

@luke-hill I don't know if I understood you; is this issue solved in the master branch? I've checked the latest commits, but didn't find anything related to this issue.

**Comment by luke-hill** [comment] 2019-01-08 09:31
I can reproduce the failure easily from your repo. Will look into this.

**Comment by luke-hill** [comment] 2019-01-08 10:45
Good news and bad news.

Good news is I've found where the issue is, and how to fix it (And I have some code I "could" push up)

Bad news. There is a warning in this area as for why we make these checks. There is also (After scanning git), some extension reasoning why this check is made. Mainly made by @aslakhellesoy around 9months ago: https://github.com/cucumber/cucumber/pull/360 - In response to a similar issue (The brackets in his issue are optional tokens, not physical brackets)

My thoughts are I'm happy to push the code up. However it adds an extra conditional in an already complex piece of functionality.

The code I have locally changes Line 54 in this range https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/cucumber_expression.rb#L52:L56 - and adds at the end `unless wanted_brackets?(expression)`

Both Aslak and @olleolleolle what are your thoughts? I'm happy to mark this as won't fix and use a custom parameterType pattern as you mentioned on the PR 9 months ago, but this is slightly different and is fixable, but adds a little more complexity.

**Comment by luke-hill** [comment] 2019-01-23 14:47
@peagha Im just going to push up the branch to the cucumber repo and go from there.

**Comment by luke-hill** [comment] 2019-03-14 15:28
As an update @peagha this is being worked on, but has raised a few more gremlins. Items are in PR / review phase at the moment

**Comment by luke-hill** [comment] 2019-03-19 08:19
@peagha This has been fixed for all bindings. A release will be forthcoming

**Closed** 2019-03-20 13:36 UTC
Labels: Slow Burner, type: bug
