### ISSUE TITLE
In command line, appending `&& say test finished` to a cucumber test doesn't work

### ISSUE THREAD

**Issue by KelseyDH** [cucumber/cucumber-ruby#1505] opened 2021-02-10 23:50 UTC
Ok, I admit this isn't critical but it's weird enough to report:

**Describe the bug**
When cucumber is run in the command line it does not give a return signal that `&&` can accept.

**To Reproduce**
1. On a Mac, run a cucumber test but append a `&&` command.  
E.g. `bundle exec cucumber my_feature.feature && say test finished`

**Expected behavior**
On Mac , the `say` command will make your computer say _"test finished!"_ out loud.  With cucumber, no sound is returned.  Other testing frameworks like `rspec` work when I append `&& say test finished`.  For cucumber, separating the commands with `;` works but `&&` annoyingly does not work.

It's not `bundler` either, commands like `bundle exec rake db:reset && say test finished` work.

**Context & Motivation**

Bringing this up as maybe something could be done to improve how cucumber parses command line arguments, or how it returns itself when chained with other commands.

**Screenshots**

**Your Environment**
 - My Gemfile.lock:
 ```
    cucumber (4.1.0)
      builder (~> 3.2, >= 3.2.3)
      cucumber-core (~> 7.1, >= 7.1.0)
      cucumber-create-meta (~> 1.0.0, >= 1.0.0)
      cucumber-cucumber-expressions (~> 10.1, >= 10.1.0)
      cucumber-gherkin (~> 14.0, >= 14.0.1)
      cucumber-html-formatter (~> 7.0, >= 7.0.0)
      cucumber-messages (~> 12.2, >= 12.2.0)
      cucumber-wire (~> 3.1, >= 3.1.0)
      diff-lcs (~> 1.3, >= 1.3, < 1.4)
      multi_test (~> 0.1, >= 0.1.2)
      sys-uname (~> 1.0, >= 1.0.2)
    cucumber-core (7.1.0)
      cucumber-gherkin (~> 14.0, >= 14.0.1)
      cucumber-messages (~> 12.2, >= 12.2.0)
      cucumber-tag-expressions (~> 2.0, >= 2.0.4)
    cucumber-create-meta (1.0.0)
      cucumber-messages (~> 12.2, >= 12.2.0)
      sys-uname (~> 1.2, >= 1.2.1)
    cucumber-cucumber-expressions (10.3.0)
    cucumber-gherkin (14.2.0)
      cucumber-messages (~> 12.4, >= 12.4.0)
    cucumber-html-formatter (7.2.0)
      cucumber-messages (~> 12.4, >= 12.4.0)
    cucumber-messages (12.4.0)
      protobuf-cucumber (~> 3.10, >= 3.10.8)
    cucumber-rails (2.1.0)
      capybara (>= 2.12, < 4)
      cucumber (>= 3.0.2, < 5)
      mime-types (>= 2.0, < 4)
      nokogiri (~> 1.8)
      rails (>= 4.2, < 7)
    cucumber-tag-expressions (2.0.4)
    cucumber-wire (3.1.0)
      cucumber-core (~> 7.1, >= 7.1.0)
      cucumber-cucumber-expressions (~> 10.1, >= 10.1.0)
      cucumber-messages (~> 12.2, >= 12.2.0)
```
 - Mac OS X Catalina 10.15.7
 - Build tool (if applicable)
   - bundle exec
   - Called from inside a Rails project.

**Additional context**
I really just want to know what cucumber is doing differently for the `&&` not to work.

**Comment by aslakhellesoy** [comment] 2021-02-11 09:58
Cucumber's exit status is `0` if all scenarios pass and no steps are undefined, otherwise it is `1`. This is by design.

So if you have failing or undefined steps, nothing after `&&` will be executed. If you always want to run something, use `;`

@KelseyDH what exit status are you getting from cucumber?

**Comment by aurelien-reeves** [comment] 2021-03-17 10:03
@KelseyDH did you had the possibility to take a look on the exit status from cucumber in your case?

**Comment by aslakhellesoy** [comment] 2021-03-30 11:53
Closing this due to lack of information.

**Closed by aslakhellesoy** 2021-03-30 11:53 UTC
Labels: :baby_bottle: incomplete, :question: question
