### ISSUE TITLE
Formatter migration path not explained

### ISSUE THREAD

**Issue by viraptor** [cucumber/cucumber-ruby#1294] opened 2018-05-11 01:30 UTC
## Summary

Migration path for the new formatter API is not explained anywhere. Due to parallel_tests, I'm getting a large number of:
```
WARNING: The formatter ... is using the deprecated formatter API which will be removed in v4.0 of Cucumber.
```
But apart from https://github.com/cucumber/cucumber-ruby/blob/c26c2d102bb72193fe299b2d25edc4e82fdbba54/features/docs/extending_cucumber/custom_formatter.feature#L44-L85 I can't find any good summary of how the new version works / differs.

The existing formatters still use the deprecated API and the wiki shows only the old format at https://github.com/cucumber/cucumber/wiki/Custom-Formatters

## Expected Behavior

Link to some explanation of the new API and possibly a migration path.

## Current Behavior

Lots of repeated warnings in every build with no explanation of how to fix them

## Possible Solution

Wiki/web page explaining the migration.

## Your Environment

* Version used: 3.1.0
* Operating System and version: MacOS 10.13
* Link to your project:

**Comment by viraptor** [comment] 2018-07-10 04:32
Still an issue for me.

**Comment by griffincox** [comment] 2018-10-18 16:35
+1

**Comment by danascheider** [comment] 2018-10-24 10:16
@viraptor @grosser I created this [minimal example](https://github.com/danascheider/cucumber_parallel_tests_example) to try to reproduce the deprecation warnings you're seeing. However, if I run my features with `parallel_cucumber features --runtime-log`, it doesn't seem to trigger the formatter to be used. What do I need to do differently to trigger one of the formatters to be used? I'm trying to create a PR to make the formatters compatible with the Cucumber events API but I need to be able to repro first.

**Comment by mlvandijk** [comment] 2018-10-25 08:47
Duplicate of: https://github.com/cucumber/docs.cucumber.io/issues/233 (?)

**Comment by danascheider** [comment] 2018-10-26 00:40
@mlvandijk Yes. I just created a PR to fix this problem in the [parallel_tests](https://github.com/grosser/parallel_tests) gem, and now I'm looking at the docs to try and improve our documentation of the new API.

**Comment by grosser** [comment] 2018-10-26 01:31
thx!

**Closed** 2018-10-26 02:07 UTC
Labels: Hacktoberfest, Type: documentation required, good first issue

**Comment by mlvandijk** [comment] 2018-10-26 05:12
That's awesome @danascheider Let me know if you need help with the docs!

**Comment by danascheider** [comment] 2018-10-26 05:15
Thanks @mlvandijk, I might. I haven't worked a whole lot with custom formatters, luckily the one that needed fixing in this case was pretty straightforward. 

Also @viraptor @griffincox Update `parallel_tests` to version 2.26.0, which just dropped today, and you should see the problem is fixed. I just merged a PR at my job updating this and the deprecation warnings went away. Let us know if the problem persists for you.

**Comment by mlvandijk** [comment] 2018-11-04 09:29
Information regarding Ruby formatters can be found here: https://docs.cucumber.io/cucumber/reporting/
