### ISSUE TITLE
Running cucumber with formatter `stepdefs` and `dry-run` fails with exception.

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-ruby#955] opened 2016-03-21 20:50 UTC
Hi @brasmusson,

any idea why `bundle exec cucumber -f stepdefs --dry-run` fails with an exception, when I'm on master?

~~~
[git:master]% bundle exec cucumber -f stepdefs --dry-run
Using the default profile...
undefined method `step_definition' for nil:NilClass (NoMethodError)
/home/user/data/projects/cucumber-ruby/lib/cucumber/formatter/usage.rb:29:in `after_test_step'
/home/user/data/projects/cucumber-ruby/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/home/user/data/projects/cucumber-ruby/lib/cucumber/formatter/legacy_api/adapter.rb:38:in `after_test_step'
/home/user/data/projects/cucumber-ruby/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/home/user/data/projects/cucumber-ruby/lib/cucumber/formatter/fanout.rb:15:in `each'
/home/user/data/projects/cucumber-ruby/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/runner.rb:27:in `test_step'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/step.rb:16:in `describe_to'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:26:in `block (3 levels) in describe_to'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:25:in `each'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:25:in `block (2 levels) in describe_to'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:107:in `compose_around_hooks'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:24:in `block in describe_to'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/runner.rb:18:in `test_case'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/user/data/projects/cucumber-ruby/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/user/data/projects/cucumber-ruby/lib/cucumber/filters/quit.rb:11:in `test_case'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/case.rb:23:in `describe_to'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/filter.rb:61:in `done'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/compiler.rb:23:in `done'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core/gherkin/parser.rb:39:in `done'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core.rb:29:in `parse'
/home/user/.gem/2.3.0/bundler/gems/cucumber-ruby-core-bf84e993e770/lib/cucumber/core.rb:18:in `compile'
/home/user/data/projects/cucumber-ruby/lib/cucumber/runtime.rb:68:in `run!'
/home/user/data/projects/cucumber-ruby/lib/cucumber/cli/main.rb:32:in `execute!'
/home/user/data/projects/cucumber-ruby/bin/cucumber:8:in `<top (required)>'
/home/user/.gem/2.3.0/bin/cucumber:23:in `load'
/home/user/.gem/2.3.0/bin/cucumber:23:in `<main>'
~~~

I'm using this "rev" of cucumber-ruby/master.

~~~
ea3d3de564146c9a7153eece065edcf48e0a45a9        refs/heads/master
~~~

Is this somehow related to https://github.com/cucumber/cucumber-ruby/commit/ea3d3de564146c9a7153eece065edcf48e0a45a9? 

The exception happend, when I wanted to figure out where the following step comes from:

~~~
    Then it should pass with exactly:
~~~

**Comment by dg-ratiodata** [comment] 2016-03-22 11:48
Duplicate of  #953.

**Closed by dg-ratiodata** 2016-03-22 11:48 UTC
