### ISSUE TITLE
Running cucumber with `Inprocess` from `aruba`

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/cucumber-ruby#886] opened 2015-07-09 15:30 UTC
Hi, I merged cucumber/aruba#258 and released a pre-release 0.8.0.pre2. Unfortunately `cucumber` does not work well with this release. 

**The problem is this:**

* Cucumber uses `Inprocess` to make tests faster
* Cucumber reads in Feature-files somewhere in the code
* It seems like it uses the current working directory for this
* It outputs the file names of the steps as well

		Feature: test
		
		Scenario:               # features/test.feature:2
		-    Given this step fails # features/step_definitions/steps.rb:4
		+    Given this step fails # tmp/aruba/features/step_definitions/steps.rb:4
		
* The tmp/aruba directory is part of the output although Dir.chdir is used
* Using the "old" gem version the problem, the problem does not occure
* Re-Using parts of the old code does not solve the problem

**What does aruba do?**
```ruby
      def run!
        fail "You need to call Aruba.process.main_class = YourMainClass" unless self.class.main_class

        Dir.chdir @working_directory do
          before_run

		  # even change `PWD` now
          in_environment 'PWD' => @working_directory do
            self.class.main_class.new(@argv, @stdin, @stdout, @stderr, @kernel).execute!
          end

          after_run

          yield self if block_given?
        end
      end
```
I placed `Dir.chdir`-calls at different places, tried some code walking, but still I didn't have an idea why `cucumber` finds the feature-files, but also outputs the `tmp/aruba`-directory? Normally it complains about a missing `feature`-directory.

Any idea where to look for the code which uses `Dir.getwd`?

BTW:
Using `SpawnProcess` works like a charm.
Thanks a lot.

Cheers, Dennis

**Comment by mattwynne** [comment] 2015-07-09 17:41
Possibly related: #885

**Comment by dg-ratiodata** [comment] 2015-07-13 10:27
Ok. I tracked it down. Puh.... The problem is the following piece of code. `cucumber` uses the `PWD` constant to calculate the path to the step file. But PWD is set when the `proc.rb`-file is loaded. At this time the working directory has not changed yet, thus PWD points to "project-root". Changing it afterwards is ignored. Is there a good reason why `cucumber` works this way? Looks a little bit weird to get `Dir.getwd` when the file is loaded by the interpreter.

`lib/cucumber/core_ext/proc.rb`:

```ruby
# [..]
  PWD = Dir.pwd
# [..]

    def file_colon_line
      path, line = *to_s.match(PROC_PATTERN)[1..2]
      path = File.expand_path(path)

######
      pwd = File.expand_path(PWD)
######
      pwd.force_encoding(path.encoding)
      if path.index(pwd)
        path = path[pwd.length+1..-1]
      elsif path =~ /.*\/gems\/(.*\.rb)$/
        path = $1
      end
      "#{path}:#{line}"
    end
```

Grepping the source, I see no reason to use a constant for this:

```
lib/cucumber/core_ext/proc.rb:5:  PWD = Dir.pwd
lib/cucumber/core_ext/proc.rb:20:      pwd = File.expand_path(PWD)
lib/cucumber/formatter/backtrace_filter.rb:13:      PWD_PATTERN = /#{::Regexp.escape(::Dir.pwd)}\//m
lib/cucumber/formatter/backtrace_filter.rb:21:        @exception.backtrace.each{|line| line.gsub!(PWD_PATTERN, "./")}
```

**Comment by brasmusson** [comment] 2015-07-13 10:38
Then this should be fixed by #888, se also the discussion in https://github.com/cucumber/cucumber-ruby/commit/af0f18440510776e0f382ba94ad1eaab3196fdc4#commitcomment-12092131

**Comment by dg-ratiodata** [comment] 2015-07-13 10:45
Mmmh... Sounds good. But I tried the branch, but the error is the same. The path needs to be calculated on runtime, not on load time. Otherwise the change of CWD gets unnoticed.

**Comment by dg-ratiodata** [comment] 2015-07-13 10:59
Ok. Seems to be a different thing. Maybe the hooks need some love too?

**Comment by dg-ratiodata** [comment] 2015-07-13 11:12
This should be fixed if both PRs #888 and #890 are merged.

**Comment by dg-ratiodata** [comment] 2015-07-13 11:20
@mattwynne 

Would be possible to backport those changes to `1.3.x` at least that the working directory is determined at runtime?

**Comment by mattwynne** [comment] 2015-07-16 21:05
Why do you want the back-port @dg-ratiodata?

**Comment by dg-ratiodata** [comment] 2015-07-17 07:36
This is only required if you would like to use aruba >= 0.7. in your 1.3.x "branch". Dir.getwd needs to be checked on runtime only not on load time. 

BTW: I added some documentation tests to make this clear for future releases and users.

**Comment by mattwynne** [comment] 2015-07-17 11:06
I don't intend to do any more releases of the 1.3 series, so this shouldn't be an issue.

**Comment by maxmeyer** [comment] 2015-07-17 11:07
Alright.

**Comment by maxmeyer** [comment] 2015-07-17 11:08
Any chance to get those fixes merged soon?

**Comment by mattwynne** [comment] 2015-08-07 00:36
Closing in favour of #888 and #890

**Closed** 2015-08-07 00:36 UTC
