### ISSUE TITLE
Add ability to include feature files and some additional data.

### ISSUE THREAD

**Issue by vveliev** [cucumber/cucumber-ruby#1076] opened 2017-02-07 14:21 UTC
## Summary
After using cucumber for about 2 years now, I have discovered some limitations to the design.

## Expected Behavior

1. Ability to reuse common features in order to avoid code duplication.
This can  partially be resolved using tags and multiple feature files in conjunction but it's very hard to keep things in order. Maybe it's not that bad to add ability to include feature files with in the feature. Or create new files extension for generating templates for specific test sets.

2. Add ability to load some configuration before run time such that, loaded data can be used to generate scenario outlines examples or be populated in to the tables. This may reduce size and duplication of example data for scenario outlines as it's common to have multiple scenario outlines with same input data. 

## Current Behavior

1. Use tags with some crazy combination of feature files.
2. Create big example tables , tag each example and duplicate table for several scenario outlines.

~~~
~~~

## Possible Solution

1.  add "include step/scenario"
2. add ability to load data with in the cucumber profiles 

## Context & Motivation

Improve work flow when working with cucumber reduce code duplication and reduce maintenance time.

## Your Environment

* Version used: 2.4
* Operating System and version: Linux

**Comment by mattwynne** [comment] 2017-03-04 01:23
Can you give me a concrete example please?

**Comment by vveliev** [comment] 2017-03-06 05:17
sure

So let's say I have  20 feature files, and my regression test include all this files in certain order.
How that should be done ?! Very long command line and then not really flexible from what I can see .

Now solution we have at this moment is based on the tempting where it generate final file combining scenarios in required order. 

1. If there we ability to include files, or something similar 
```
Feature: Multiple files 

  Scenario Include:  fatures/user_permissions.feture 
```

2. We have been in the situation where there are simply too many steps for single scenario outline and we end up having multiple Examples tables duplicated across multiple feature files (abound 60 entries each table) 

So I was thinking of adding some sort of options that can be load in cucumber.yml file or so:
Feature:
```
Feature: Multiple files 

  Scenario Outline:

    Examples: @@users
```
cucumber.yml
```
default: --color -f pretty --include_examples data/examples.yml
```
examples.yml

```
users: 
  __tags__: [user]  # tags applied to entire example table
  data:
    - __tags__: [simple, default]
       username: test
       password: test123
    - __tags__: [admin]
      username: admin
      password: admin
```

so this would be equivalent to:

```
Feature: Multiple files 

  Scenario Outline:
    Step 1
    Step 2
   @user @simple @defult
    Examples:
       |usersname|password|
       |test            | test123   |
   @user @admin
    Examples:
       |usersname|password|
       |admin        | admin     |
```

**Comment by vveliev** [comment] 2017-03-07 16:18
Another use will be some times depending what environment is being test, you may need different scenario outline data.

**Comment by danascheider** [comment] 2017-04-03 16:40
@vveliev To tell you the truth, some of what you're describing sounds like an anti-pattern to me. I usually advise people that having too many data tables or out-of-control scenario outlines can be a sign you're operating at too low a level of abstraction in your steps. It sounds to me like you'd benefit from pulling some logic out of your steps and moving it into step definitions and helper modules. @mattwynne thoughts?

**Comment by vveliev** [comment] 2017-04-04 05:56
@danascheider Let's take "car" as example, now we need to write regression for "cars":
what do we have?!
-sport cars 
-minivan's
-have track
-suv
-tractors
-specialty vehicles
- etc.

They  all have common things and also some special attributes. 
now let's say I have 60 different types of cars ....I want a single regression to handle them all.

Now let's assume I have a scenario outline that does negative test for the tire's size. or something. 


1.  The thing that's i'm running in to now is that I may end up with huge example table that looks afoul 
```
   Scenario Outline:
    Step 1
    Step 2
   @suv
    Examples:
       |tire|error|
       |size 23            | 23 is big for suv  |
   @suv
    Examples:
       |tire|error|
       |size 10        | 10 is small for suv     |
```
 So i'm ending up with table that have more then 50 entries, i'm using hooks to skipping 90% of the table and only 10% is used for one particular car type .

2. let's say we have big example's table with 30-50 lines and we are doing positive and negative testing, what is the point of duplicating this table for positive and negative testings ?!



Maybe there is a better way of testing this but , I don't see it , and maybe some one can show me a better approach.

 It's possible to use cucumber profiles , and different files .... but then you end up with 50 files that have duplicated Scenario outlines and maintenance of those may not be a pleasant experience.

**Comment by mattwynne** [comment] 2017-04-04 08:41
@vveliev I wonder if [suites](https://github.com/cucumber/cucumber-ruby/issues/821) might be the solution you're looking for?

**Comment by mattwynne** [comment] 2017-04-28 19:50
Gherkin is not a programming language. It's designed for expressing human-readable acceptance test cases for feedback before and during development. It's not designed for regression testing. If you want complex test scripting, I would use a programming language.

**Comment by mattwynne** [comment] 2017-04-28 19:53
Closing due to inactivity. I do appreciate your feedback @vveliev and if we can break down your ideas into some smaller pieces, perhaps we can discuss one or two of the most high-value ones in separate tickets. I'm finding it hard to help with this ticket as there seem to be so many ideas and problems floating around I don't know where to start ! 😀

**Closed by mattwynne** 2017-04-28 19:53 UTC
