### ISSUE TITLE
Cant generate cucumber report - html image

### ISSUE THREAD

**Issue by emiliamariaa9933** [cucumber/cucumber-ruby#1509] opened 2021-02-27 01:50 UTC
I'm having trouble trying to execute cucumber report. As the pic shows, It couldn't display attachment because the media type is unsupported. Idont know ho to solve it. Ive tried to update to cucumber 4.1.0 and 5.3.0, no success.

helper.rb:

require "fileutils"

module Helper
  def take_screenshot(file_name, result)
    timer_path = Time.now.strftime("%F").to_s
    file_path = "results/screenshots/test_#{result}/run_#{timer_path}"
    screenshot = "#{file_path}/#{file_name}.png"
    page.save_screenshot(screenshot)
    attach("image/png;base64", screenshot)
  end
end

---------------------------------------------------
hooks.rb:

World(Helper)

After do |scenario|
  scenario_name = scenario.name.gsub!(/\s+/, "_")
  scenario_name = scenario.name.delete(",", "")
  scenario_name = scenario.name.delete("(", "")
  scenario_name = scenario.name.delete(")", "")
  scenario_name = scenario.name.delete("#", "")

  if scenario.failed?
    urlSLCEF = page.current_url
    titulePagina = page.title

    $logger.info("Capturando screenshot de falha ocorrida em:" + " " + titulePagina + "-" + urlSLCEF)
    take_screenshot(scenario_name.downcase!, "failed")
  else
    $logger.info("Capturando screenshot do sucesso")
    take_screenshot(scenario_name.downcase!, "passed")
  end
end

![error](https://user-images.githubusercontent.com/61381569/109371720-efda2800-7884-11eb-8206-192c89a86aa6.jpg)

**Comment by luke-hill** [comment] 2021-03-01 10:08
Duplicate of https://github.com/cucumber/cucumber-ruby/issues/1506

**Closed by luke-hill** 2021-03-01 10:08 UTC
